before:
  hooks:
    - go mod tidy

builds:
  - id: "ha-fronius-bm"
    binary: bin/ha-fronius-bm
    env:
      - CGO_ENABLED=0
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"