before:
  hooks:
    - go mod tidy

builds:
  - id: "check-amount-integrity"
    binary: bin/check-amount-integrity
    env:
      - CGO_ENABLED=0
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"